services:
  postgres:
    image: postgres:15
    container_name: doe_postgres
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: doe_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: doe_minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio-init:
    image: minio/mc:latest
    container_name: doe_minio_init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      /bin/sh -c "
      mc alias set local http://minio:9000 minio_admin minio123456 && \
      mc mb -p local/raw || true && \
      mc mb -p local/processed || true && \
      mc mb -p local/results || true && \
      mc policy set public local/results || true
      "

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: doe_airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__RBAC: "true"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin123
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio123456
      MINIO_BUCKET_RAW: raw
      MINIO_BUCKET_PROCESSED: processed
      MINIO_BUCKET_RESULTS: results
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "
      airflow db migrate && \
      airflow users create \
        --username $$_AIRFLOW_WWW_USER_USERNAME \
        --password $$_AIRFLOW_WWW_USER_PASSWORD \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com || true && \
      airflow webserver
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: doe_airflow_scheduler
    depends_on:
      airflow-webserver:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio123456
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - airflow_logs:/opt/airflow/logs
    command: ["airflow", "scheduler"]

  airflow-worker:
    image: apache/airflow:2.9.3
    container_name: doe_airflow_worker
    depends_on:
      airflow-webserver:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/1
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio123456
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - airflow_logs:/opt/airflow/logs
    command: ["airflow", "celery", "worker"]

volumes:
  postgres_data:
  airflow_logs:
  minio_data:
